### ISSUE TITLE
[Root-Task] 스타일링

### ISSUE THREAD

**Issue by juo1221** [juo1221/toons#1]
### Todo
 - [x] side tab 스타일링
 - [x]  TabView 코드 수정
 - [x]  searchBar 스타일링
 - [x] DateView 스타일링
 - [x] FilteringView 스타일링
 - [x] SortView 스타일링
 - [x] CardListView 스타일링
 - [x] 전체적으로 다듬기
 - [x] 스크롤바 제거
 - [x] text 숨기기
 - [x] 마우스 hover 시 카드 zoom-in 에니메이션 적용
 - [x] hoverCard 텍스트 hide 추가
 - [x] font 설정
