### ISSUE TITLE
[Root-Task] 기능추가

### ISSUE THREAD

**Issue by juo1221** [juo1221/toons#2]
### Todo
 - [x] dateView에 현재 요일 적용하기 
 - [x] 초기 웹툰 데이터 불러오기
 - [x] 요일별 웹툰 데이터 불러오기 
 - [x] platForm 별 렌더링 기능 구현
 - [x] 이름변경 및 자잘한 수정
 - [x] WebToonDataStore 분리
 - [x] MyListStore 추가
 - [x] 좋아요 기능 추가
 - [x] 제목으로 filtering 기능 구현 
 - [x] observer 추가
 - [x] 파일 설정
 - [x] 정렬 기능 구현
 - [x] search 기능 구현
 - [x] 필터링 초기화 기능추가
 - [x] 검색 초기화 기능추가
 - [x] hoverCard 좋아요 기능 추가
 - [x] 링크 기능 추가
 - [x] 로딩 전 UI 작업
 - [x] 마이리스트 추가 전 No 표시 추가
 - [x] 데이터 로딩 전 UI 작업 완료
 - [x] 애니메이션 작업 추가
