### ISSUE TITLE
[Fix] 수정

### ISSUE THREAD

**Issue by juo1221** [juo1221/toons#3]
### Todo
 - [x] heart 아이콘 위치 에러 수정 
 - [x] 폰트 적용 문제 해결
 - [x] 반응형 스타일 추가
 - [x] #6
