### ISSUE TITLE
[Refactor] 리팩토링

### ISSUE THREAD

**Issue by juo1221** [juo1221/toons#4]
### Todo
 - [x] jpeg => webp 적용
 - [x] intersection observer를 이용해 lazyLoading
 - [x] react-icons 용량 축소
 - [x] lodash 사이즈 축소
